LANGUAGES = {
    'hello': 'Пртвет!',
    'renter': 'русча beruvchi',
    'client': 'Кдиент',
    'choose_lang': 'Выберите язык:',
    'bir_narsa': 'вы выбрали русский',
    'lang_uz': "O'zbekcha",
    'lang_ru': "Русский", 
    'lang_en': "English", 
    'unknown_user': 'дорогой пользователь',
    'for_search': 'введите адрес для поиска: ',
    'enter_address': 'введите адрес дома: ',
    'enter_description': 'дайте краткую информацию про дома: ',
    'enter_location': 'введите точную локацию',
    'enter_cost': 'введите стоимость(только цифры)',
    'enter_contact': 'отправьте номер телефона(нажимая кнопку снизу)',
    'contact_button': 'номер вашего телефона',
    'location': 'отвпраьте локацию дома',
    'photos': 'отвпраьте фотографии дома',
    'enter_ready': 'спасибо, информация сохранена.',
    'unknown_message': 'ошибка!',
    'enter_end': 'не понял!',
    'for_search_text': 'введите тескт для поиска'
}
