LANGUAGES = {
    'hello': 'Salom!',
    'renter': 'E’lon berish',
    'client': 'E’lon izlash',
    'choose_lang': 'Tilni tanlang: ',
    'choose_action': 'Quyidagi amallardan birini tanlang:',
    'lang_uz': "O'zbekcha",
    'lang_ru': "Русский", 
    'lang_en': "English", 
    'unknown_user': 'Hurmatli foydalanuvchi',
    'for_search': 'Izlash uchun manzil kiriting: ',
    'enter_address': 'Uy manzilini kiriting: ',
    'enter_description': 'Uy haqida qisqa ma`lumot kiriting: ',
    'enter_location': 'Aniq lokatsiyasini yuboring',
    'enter_cost': 'Narxini (faqat raqamlar bilan) kiriting',
    'enter_contact': 'Telefon raqamingizni yuboring (pastdagi tugmani bosib)',
    'contact_button': 'Telefon raqamingiz',
    'location': 'Uy joylashuvini yuboring',
    'photos': 'rasmnlarni yuklang',
    'enter_ready': 'Rahmat, ma`lumotlar saqlandi.',
    'unknown_message': 'hato!',
    'enter_end': 'Tushunmadim!',
    'for_search_text': 'Izlash uchun matn kiriting',
    'enter_founded': 'Topilgan e`lonlar chiqarildi.',
    'enter_not_found': 'So`rov bo`yicha topilmadi.'
}   
