LANGUAGES = {    
    'hello': 'Hello!',
    'renter': 'renter',
    'client': 'client',
    'choose_lang': 'choose language: ',
    'choose_action': 'you choose english',
    'lang_uz': "O'zbekcha",
    'lang_ru': "Русский", 
    'lang_en': "English", 
    'unknown_user': 'Dear user',
    'for_search': 'enter text for search: ',
    'enter_address': 'enter address: ',
    'enter_description': 'brief information about home: ',
    'enter_location': 'send location',
    'enter_cost': 'cost(only numbers)',
    'enter_contact': 'telephone number (press button in below)',
    'contact_button': 'telephone number',
    'location': 'send home location',
    'photos': 'send photos',
    'enter_ready': 'thank you, information saved.',
    'unknown_message': 'error!',
    'enter_end': 'not understand!',
    'for_search_text': 'enter text for searching',
    'enter_founded': 'finded advertisements showed.',
    'enter_not_found': 'nothing founded on request.',
}